### ISSUE TITLE
Not work on Magento version 2.1.13 and 2.1.14

### ISSUE THREAD

**Issue by AlexDidkovskiy** [SlavaYurthev/MultipleLayeredNavigation-M2#3]
I have error

**Comment by AlexDidkovskiy** [comment]
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_ids_index.category_id' in 'where clause', query was: INSERT INTO `search_tmp_5b75a7eeb16236_50140388` SELECT `main_select`.`entity_id`, MAX(score) AS `relevance` FROM (SELECT `search_index`.`entity_id`, (((0) + (0)) * 1) AS `score` FROM `catalogsearch_fulltext_scope1` AS `search_index`
 LEFT JOIN `catalog_eav_attribute` AS `cea` ON search_index.attribute_id = cea.attribute_id
 INNER JOIN `catalog_category_product_index` AS `category_products_index` ON search_index.entity_id = category_products_index.product_id
 LEFT JOIN `cataloginventory_stock_status` AS `stock_index` ON search_index.entity_id = stock_index.product_id AND stock_index.website_id = 0 WHERE (stock_index.stock_status = 1) AND (category_ids_index.category_id = 4) AND (category_products_index.`visibility` IN ('2', '4'))) AS `main_select` GROUP BY `entity_id` ORDER BY `relevance` DESC
 LIMIT 10000
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_ids_index.category_id' in 'where clause'

**Comment by AlexDidkovskiy** [comment]
I tried to install your extension on the latest versions 2.1.13 and 2.1.14. Category pages show errors.

**Comment by SlavaYurthev** [comment]
this are not supported versions
