### ISSUE TITLE
category filter not working

### ISSUE THREAD

**Issue by to8gal** [SlavaYurthev/MultipleLayeredNavigation-M2#4]
It seems like the category filter is not working

**Comment by SlavaYurthev** [comment]
all base described functionality has been tested by magento team

**Comment by to8gal** [comment]
ok this does not really help solve the problem:

Also if you mean for "described functionality" the guidelines.pdf in your directory that really lacks in describe generally.
I am on 2.2.4, which Magento version they test? and what PHP? mine is 7.0.30 on a Xampp on High Sierra OS, what else do you need to know?

Hope you can help me find the problem

Thanks

L
